# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path pathlists to be prepended to sys.path and in backends.
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow array encoding of revision dates
# during 'history' and 'show'
# version_locations = %(here)s/bar:%(here)s/bat:versions

# version table name; default is alembic_version
# version_table = alembic_version

# version table schema; default is None
# version_table_schema = None

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/aiops

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
datefmt = %H:%M:%S
