"""Add incident_decisions table

Revision ID: 2dfae43fd967
Revises: 0a6b12ccc789
Create Date: 2026-06-10 10:30:09.525293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfae43fd967'
down_revision: Union[str, None] = '0a6b12ccc789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('business_impact_score', sa.Float(), nullable=False),
    sa.Column('technical_impact_score', sa.Float(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('affected_services', sa.Text(), nullable=True),
    sa.Column('similar_incident_count', sa.Integer(), nullable=True),
    sa.Column('gitlab_issue_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['log_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_decisions_analysis_id'), 'incident_decisions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_incident_decisions_id'), 'incident_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_incident_decisions_log_id'), 'incident_decisions', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_decisions_log_id'), table_name='incident_decisions')
    op.drop_index(op.f('ix_incident_decisions_id'), table_name='incident_decisions')
    op.drop_index(op.f('ix_incident_decisions_analysis_id'), table_name='incident_decisions')
    op.drop_table('incident_decisions')
    # ### end Alembic commands ###
