"""Add GitlabIssue and IssueActivity models

Revision ID: b9be9466d549
Revises: 2dfae43fd967
Create Date: 2026-06-11 13:23:53.302025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9be9466d549'
down_revision: Union[str, None] = '2dfae43fd967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
