"""add_rca_tables

Revision ID: ec40b13194b1
Revises: 0001
Create Date: 2026-06-08 15:32:52.319193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec40b13194b1'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('root_cause_category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('technical_impact', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_analyses_id'), 'log_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_log_analyses_log_id'), 'log_analyses', ['log_id'], unique=False)
    op.create_table('analysis_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('dependency', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['log_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_dependencies_analysis_id'), 'analysis_dependencies', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_dependencies_id'), 'analysis_dependencies', ['id'], unique=False)
    op.create_table('analysis_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['log_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_patterns_analysis_id'), 'analysis_patterns', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_patterns_id'), 'analysis_patterns', ['id'], unique=False)
    op.create_table('analysis_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['log_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_services_analysis_id'), 'analysis_services', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_services_id'), 'analysis_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_services_id'), table_name='analysis_services')
    op.drop_index(op.f('ix_analysis_services_analysis_id'), table_name='analysis_services')
    op.drop_table('analysis_services')
    op.drop_index(op.f('ix_analysis_patterns_id'), table_name='analysis_patterns')
    op.drop_index(op.f('ix_analysis_patterns_analysis_id'), table_name='analysis_patterns')
    op.drop_table('analysis_patterns')
    op.drop_index(op.f('ix_analysis_dependencies_id'), table_name='analysis_dependencies')
    op.drop_index(op.f('ix_analysis_dependencies_analysis_id'), table_name='analysis_dependencies')
    op.drop_table('analysis_dependencies')
    op.drop_index(op.f('ix_log_analyses_log_id'), table_name='log_analyses')
    op.drop_index(op.f('ix_log_analyses_id'), table_name='log_analyses')
    op.drop_table('log_analyses')
    # ### end Alembic commands ###
