import logging
import json
from typing import Optional, List
import gitlab
import urllib3

# Suppress SSL verification warnings for internal GitLab connection
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from sqlalchemy.orm import Session
from sqlalchemy import select

from app.core.config import settings
from app.models.models import IncidentDecision, GitlabIssue, IssueActivity, LogAnalysis
from app.repositories.repositories import app_setting_repo

logger = logging.getLogger(__name__)

GITLAB_URL_SETTING = "gitlab_url"
GITLAB_TOKEN_SETTING = "gitlab_private_token"
GITLAB_PROJECT_ID_SETTING = "gitlab_project_id"


def get_gitlab_config(db: Session) -> dict:
    """DB-stored values (set via Settings) take precedence over .env, so the
    integration is fully configurable from the UI without a redeploy."""
    return {
        "url": app_setting_repo.get(db, GITLAB_URL_SETTING) or settings.GITLAB_URL,
        "token": app_setting_repo.get(db, GITLAB_TOKEN_SETTING) or settings.GITLAB_PRIVATE_TOKEN,
        "project_id": app_setting_repo.get(db, GITLAB_PROJECT_ID_SETTING) or settings.GITLAB_PROJECT_ID,
    }


def is_gitlab_configured(db: Session) -> bool:
    config = get_gitlab_config(db)
    return bool(config["url"] and config["token"] and config["project_id"])


class GitlabAgent:
    def _get_client(self, db: Session):
        """
        Resolves config and builds a client fresh on every call (rather than
        once at import time) so a config change made in Settings takes effect
        immediately, with no app restart needed.
        """
        config = get_gitlab_config(db)
        if not (config["url"] and config["token"] and config["project_id"]):
            return None, None
        try:
            gl = gitlab.Gitlab(url=config["url"], private_token=config["token"], ssl_verify=False)
            return gl, config["project_id"]
        except Exception as e:
            logger.error(f"Failed to initialize GitLab client: {e}")
            return None, None

    def _format_issue_description(self, decision: IncidentDecision) -> str:
        """Format a rich Markdown description for the GitLab issue."""
        desc = []
        
        # Header
        desc.append(f"## Incident Report: {decision.priority}")
        desc.append(f"**Log ID:** {decision.log_id}")
        if decision.affected_services:
            try:
                services = json.loads(decision.affected_services)
                desc.append(f"**Affected Services:** {', '.join(services)}")
            except:
                desc.append(f"**Affected Services:** {decision.affected_services}")
        
        desc.append(f"**Recommended Action:** {decision.recommended_action}\n")
        
        # Triage Rationale
        desc.append("### Triage Rationale")
        desc.append(decision.rationale + "\n")
        
        # RCA Details if available
        if decision.analysis:
            analysis: LogAnalysis = decision.analysis
            desc.append("### Root Cause Analysis")
            desc.append(f"**Root Cause Category:** {analysis.root_cause_category}")
            desc.append(f"**Severity:** {analysis.severity}")
            desc.append(f"**Confidence Score:** {analysis.confidence_score}\n")
            
            desc.append("#### Root Cause")
            desc.append(analysis.root_cause + "\n")
            
            if analysis.business_impact:
                desc.append("#### Business Impact")
                desc.append(analysis.business_impact + "\n")
                
            if analysis.technical_impact:
                desc.append("#### Technical Impact")
                desc.append(analysis.technical_impact + "\n")
                
            if analysis.recommendation:
                desc.append("#### Recommendation")
                desc.append(analysis.recommendation + "\n")
        
        desc.append("---\n*Auto-generated by AIOps Platform*")
        return "\n".join(desc)

    def create_issue(self, db: Session, decision_id: int) -> Optional[GitlabIssue]:
        """Creates an issue in GitLab and stores it in the local database."""
        gl, project_id = self._get_client(db)
        if not gl:
            logger.warning("GitLab Agent is not configured. Skipping issue creation.")
            return None

        # Fetch the decision
        decision = db.scalar(select(IncidentDecision).where(IncidentDecision.id == decision_id))
        if not decision:
            logger.error(f"IncidentDecision {decision_id} not found.")
            return None
            
        # Check if it already exists
        existing_issue = db.scalar(select(GitlabIssue).where(GitlabIssue.incident_decision_id == decision.id))
        if existing_issue:
            logger.info(f"GitLab Issue already exists for Decision {decision.id}.")
            return existing_issue

        try:
            project = gl.projects.get(project_id)

            title = f"[AIOps] {decision.priority} Incident in {decision.log.service_name if decision.log else 'Service'}"
            description = self._format_issue_description(decision)
            labels = ["AIOps", decision.priority, "auto-generated"]
            
            # Create the issue in GitLab
            issue = project.issues.create({
                'title': title,
                'description': description,
                'labels': labels
            })
            
            # Save to local database
            db_issue = GitlabIssue(
                incident_decision_id=decision.id,
                gitlab_issue_id=issue.id,
                gitlab_issue_iid=issue.iid,
                web_url=issue.web_url,
                title=issue.title,
                state=issue.state,
                labels=json.dumps(issue.labels),
            )
            db.add(db_issue)
            
            # Update the decision to have the gitlab issue ID
            decision.gitlab_issue_id = str(issue.id)
            
            db.commit()
            db.refresh(db_issue)
            
            # Log initial activity
            activity = IssueActivity(
                gitlab_issue_id=db_issue.id,
                action_type="created",
                description=f"Issue created in GitLab: {issue.web_url}"
            )
            db.add(activity)
            db.commit()
            
            logger.info(f"Successfully created GitLab issue {issue.iid} for decision {decision.id}")
            return db_issue

        except Exception as e:
            logger.error(f"Failed to create GitLab issue: {e}", exc_info=True)
            db.rollback()
            return None

    def sync_issues(self, db: Session) -> List[GitlabIssue]:
        """Fetches latest status for all tracked open issues and updates local DB."""
        gl, project_id = self._get_client(db)
        if not gl:
            return []

        open_issues = db.scalars(select(GitlabIssue).where(GitlabIssue.state != "closed")).all()
        updated_issues = []

        try:
            project = gl.projects.get(project_id)
            for db_issue in open_issues:
                try:
                    gl_issue = project.issues.get(db_issue.gitlab_issue_iid)
                    
                    changes = []
                    if db_issue.state != gl_issue.state:
                        changes.append(f"Status changed from {db_issue.state} to {gl_issue.state}")
                        db_issue.state = gl_issue.state
                        
                    gl_assignee = gl_issue.assignee['username'] if gl_issue.assignee else None
                    if db_issue.assignee != gl_assignee:
                        changes.append(f"Assignee changed from {db_issue.assignee} to {gl_assignee}")
                        db_issue.assignee = gl_assignee
                        
                    if changes:
                        db.commit()
                        db.refresh(db_issue)
                        updated_issues.append(db_issue)
                        
                        # Add activity records
                        for change in changes:
                            activity = IssueActivity(
                                gitlab_issue_id=db_issue.id,
                                action_type="status_change" if "Status" in change else "assignment",
                                description=change
                            )
                            db.add(activity)
                        db.commit()
                        
                except Exception as e:
                    logger.error(f"Failed to sync issue {db_issue.gitlab_issue_iid}: {e}")
                    
        except Exception as e:
            logger.error(f"Failed to sync GitLab issues: {e}")
            
        return updated_issues

gitlab_agent = GitlabAgent()
